Repository code-gambit/VT-lambdas, pull requests merged in 2021-04, with the labels that each got.

#17 Fixes 16: Now setup.py can build and created nested lambdas
  lambdas/setup.py
Labels: critical

#28 lambda@fileDelete and lambda@fileUpload
  lambdas/file_access_patterns/lambda_for_fileDelete/index.js
  lambdas/file_access_patterns/lambda_for_fileDelete/package.json
  lambdas/file_access_patterns/lambda_for_fileUpload/index.js
  lambdas/file_access_patterns/lambda_for_fileUpload/package.json
Labels: new-lambda

#49 Fixes #46: create-user modified to support post confirmation cognito flow
  lambdas/user_access_patterns/lambda_for_createUser/index.js
  lambdas/user_access_patterns/out/lambda_for_createUser.zip
Labels: update
