Repository code-gambit/VT-lambdas, pull requests merged in 2021-06, with the labels that each got.

#79 Default url on file upload implemented
  lambdas/file_access_patterns/lambda_for_fileUpload/index.js
  lambdas/url_access_patterns/lambda_for_generateURL/index.js
  lambdas/url_access_patterns/lambda_for_generateURL/package.json
Labels: enhancement, update

#83 file delete lambda modified to return entire file object after deletion
  lambdas/file_access_patterns/lambda_for_fileDelete/index.js
Labels: update

#86 Merging dev into master
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Api/model.md
  DynamoDB/CreateTable.js
  README.md
  lambdas/file_access_patterns/lambda_for_fileDelete/index.js
  lambdas/file_access_patterns/lambda_for_fileDelete/package.json
  lambdas/file_access_patterns/lambda_for_fileDetails/index.js
  lambdas/file_access_patterns/lambda_for_fileDetails/package.json
  lambdas/file_access_patterns/lambda_for_fileList/index.js
  lambdas/file_access_patterns/lambda_for_fileList/package.json
  lambdas/file_access_patterns/lambda_for_fileUpload/index.js
  lambdas/file_access_patterns/lambda_for_fileUpload/package.json
  lambdas/setup.py
  lambdas/url_access_patterns/lambda_for_deleteURL/index.js
  lambdas/url_access_patterns/lambda_for_deleteURL/package.json
  lambdas/url_access_patterns/lambda_for_generateURL/index.js
  lambdas/url_access_patterns/lambda_for_generateURL/package.json
  lambdas/url_access_patterns/lambda_for_updateURL/index.js
  lambdas/url_access_patterns/lambda_for_updateURL/package.json
  lambdas/url_access_patterns/lambda_for_urlList/index.js
  lambdas/url_access_patterns/lambda_for_urlList/package.json
  lambdas/user_access_patterns/lambda_for_createUser/index.js
  lambdas/user_access_patterns/lambda_for_createUser/package.json
  lambdas/user_access_patterns/lambda_for_crud/index.js
  lambdas/user_access_patterns/lambda_for_getUser/index.js
  lambdas/user_access_patterns/lambda_for_getUser/package.json
Labels: :star2: Priority, update
